<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MemoryAnalyzer.Core\MemoryAnalyzer.Core.csproj" />
    <ProjectReference Include="..\MemoryAnalyzer.Windows\MemoryAnalyzer.Windows.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
